version: "3.5"

networks:
  docker-registry:
    name: docker-registry-network
    driver: overlay

volumes:
  docker-registry:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/docker/registry

services:
  docker-registry:
    image: registry:2
    container_name: docker-registry
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports: 
      - "5000:5000"
    restart: always
    networks: 
      - docker-registry
    volumes:
      - docker-registry:/var/lib/registry
    logging:
      driver: "json-file"
      options:
        max-size: "20mb"
        max-file: "10"